### ISSUE TITLE
Critical error

### ISSUE THREAD

**Issue by gergo85** [mplodowski/backupmanager-plugin-public#10]
I get the following error message when I try to log in to the back-end area:  
Class 'Olssonm\BackupShield\BackupShieldServiceProvider' not found

My October build is 437. I use the latest version of your plugin.

**Comment by mplodowski** [comment]
October Gateway has a problem to generate `vendor` folder. I reported this yesterday and I am waiting for response.

For now the only solution I can give you is to grab `composer.json` file and copy it to plugin destination. Then run `composer install` in your project path. That should install missing dependencies.

**Comment by gergo85** [comment]
Thanks for the fast reply!

**Comment by mplodowski** [comment]
Please update to version 3.0.2.

**Comment by gergo85** [comment]
It works perfectly again. Thank you!
