### ISSUE TITLE
not available proc_open

### ISSUE THREAD

**Issue by m3rciful** [mplodowski/backupmanager-plugin-public#11]
What should I do if my provider does not support function '**proc_open**'? I already bought an add-on, but this was not written in the documentation.

**Comment by zakir1929** [comment]
I have the same question as @m3rciful has. I would request plugin author to please let us know what we do in this situation.

Thanks

**Comment by mplodowski** [comment]
Hi, 

sorry for late response.

This function is required to run external services on server that runs database backups. Plugin will be useless without them.

The only solution is to change server provider or use built in solutions in server panel.

I will add the note to documentation.
