### ISSUE TITLE
Memory Exhausted

### ISSUE THREAD

**Issue by gavinworks** [mplodowski/backupmanager-plugin-public#12]
Hi,

Everything working perfectly when using scheduler and artisan commands for database backups. However when I try application backups it always fails. The file size is pretty big. Anything I can do to make it work? Here's the backup log error message I get

```

View latest backup log
Starting backup...
Dumping database jwwood...
Determining files to backup...
Zipping 8429 files...
Created zip containing 8429 files. Size is 975.39 MB
Applying password and encryption to zip...
PHP Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 1022781752 bytes) in /home/forge/jww.co.uk/plugins/renatio/backupmanager/vendor/nelexa/zip/src/PhpZip/Model/Entry/ZipNewEntry.php on line 50


[Symfony\Component\Debug\Exception\FatalErrorException] 
Allowed memory size of 536870912 bytes exhausted (tried to allocate 1022781 
752 bytes) 

```

Many thanks,
Gavin

**Comment by mariavilaro** [comment]
Same problem here. Database backups run ok but can't make application backups work.

**Comment by abass** [comment]
Running into the same issue here. Is this plugin abandoned by chance? One of my favorite plugins, it started having this issue after upgrading to the most recent version though 😢

The error message is as follows (replaced with website.com):
![image](https://user-images.githubusercontent.com/5505994/68066455-ba640f80-fd0e-11e9-8def-77fe9a9357cb.png)

**Comment by mplodowski** [comment]
Hi, 

sorry for late response.

There was some issue with encryption. This should be resolved in the newest version with some new additions.

Please upgrade and let me know if this works for you.

**Comment by gavinworks** [comment]
Hi I moved to the Jamstack months ago but thanks for the update!
