### ISSUE TITLE
No backend installation

### ISSUE THREAD

**Issue by rene-mdd** [mplodowski/backupmanager-plugin-public#13]
Hi. I bought this plugin a couple of days ago, and I can't find a way to install it. I used the add project feature in the oficial website of the plugin and still it does not appear in  in the backend. Where can I download it so I can installanually install it like I have done with my others plugins? Or is there other way around?

Thanks very much.

**Comment by mplodowski** [comment]
Hi Rene,

after you add plugin to project on October website, you must attach project ID to your installation.

Please read this section: https://octobercms.com/help/site/projects

After you do this, you just click Check for updates button and plugin should be ready for installation.

**Comment by mplodowski** [comment]
If this issue is still relevant or you would like to see it actioned, please respond and I will re-open this issue.
