### ISSUE TITLE
No Filter to select Tables

### ISSUE THREAD

**Issue by syehan** [mplodowski/backupmanager-plugin-public#14]
Hi, I love to use your plugin in my project, thank you very much.

But I have some issue in my server when execute the backup process.
By the way my server is minimum specifications. so my server down in couple of minute, and then **I was lookup my monitoring server also the database server, the result of analytic that freeable memory in my database has drop to 0 MB**, _it cause the app cant access the database_, and I realize that some log table like event_log, mail_log and stuff like that is following to do backup, those size can be compare to app size itself.. :) maybe if we have a table filter to minimize the vulnerability like this came again.

once again thank you..

**Comment by mplodowski** [comment]
In the newest version this is possible in backend Settings. The October logs tables will be excluded by default.

![Zrzut ekranu 2020-06-19 o 08 18 51](https://user-images.githubusercontent.com/6774277/85102758-94d83780-b205-11ea-815e-01bb39ba1376.png)
