### ISSUE TITLE
Uploading to Dropbox fails

### ISSUE THREAD

**Issue by Janjanus** [mplodowski/backupmanager-plugin-public#15]
I am experiencing issues when uploading the backups to dropbox. See the following log

```
Starting backup...
Dumping database octobercms...
Determining files to backup...
Zipping 841 files...
Created zip containing 841 files. Size is 29.6 MB
Applying password and encryption to zip...
Successfully applied password and encryption to zip.
Copying zip to disk named dropbox...
Successfully copied zip to disk named dropbox.
Copying zip failed because: The Dropbox API v2 does not support mimetypes. Given path: `Example/example2019-12-18-17-06-44.zip`..
Backup completed!
```

The problem occurs in the flysystem-dropbox. See the following issue: https://github.com/spatie/flysystem-dropbox/issues/29. Upgrading the flysystem-dropbox from the Dropbox adapter would solve this problem. Please note that the BackupManager says that the backup succeeded but in-fact it failed.

**Comment by johnnywo** [comment]
I am facing the same problem with Dropbox. Would appreciate a solution. Thank you

**Comment by mplodowski** [comment]
Please upgrade https://octobercms.com/plugin/renatio-dropboxadapter to newest version.
