### ISSUE TITLE
Parse error: syntax error, unexpected '?'

### ISSUE THREAD

**Issue by Exodon** [mplodowski/backupmanager-plugin-public#16]
Hi
I´m having a error when I tried to create the backup of the October cms website. Basically I install everything and add all the settings but when I click on **application backup** or **database backup** it gives me this output : `Parse error: syntax error, unexpected '?'`

![Screen Shot 2020-07-06 at 08 56 09](https://user-images.githubusercontent.com/3321409/86564562-b86de280-bf66-11ea-850a-97a694c9c1f8.png)

**Comment by mplodowski** [comment]
What version of PHP and October you have installed?

Please check Latest backup log if there is some more info. Also check the Event Logs in October Settings.

**Comment by Exodon** [comment]
thanks for the fast reply...

About your first question...I need to check the php version. About the October CMS I think I have the latest.

**This is the error log :**

`Symfony\Component\Debug\Exception\FatalThrowableError: Parse error: syntax error, unexpected '?' in /home/didgenat/public_html/portal/plugins/renatio/backupmanager/vendor/spatie/laravel-backup/src/BackupDestination/BackupDestination.php:147

I have the version **3.3.3** of your plugin
`
I choose **local** as destination to saved the backup.

**Comment by mplodowski** [comment]
This plugin requires PHP 7.1 version or later. 

It looks by the error you have version PHP 7.0.

Please try to upgrade PHP and let me know if it works.

**Comment by Exodon** [comment]
@mplodowski can this affect other plugins ? if I move to PHP 7.1 ?

**Comment by mplodowski** [comment]
It should not if those plugins are still maintained.

The 7.0, 7.1 version are old and not supported any more.

October CMS soon will upgrade to Laravel 6 and there is min. requirement of PHP 7.2.

In my opinion you should upgrade to at least version 7.2, but I recommend you 7.3 or 7.4. 

October supports latest version of 7.4 and most of the plugins should as well.

https://en.wikipedia.org/wiki/PHP#Release_history

**Comment by Exodon** [comment]
Hi again

I noticed that my production server has php 7.0 . Was a bit scary but I turned the version 7.3 but the website basically stop working, then I revert back to 7.0.  Any recommendation to follow ?

**Comment by mplodowski** [comment]
On production I would try to use 7.1 and if it works than try 7.2.

As for your local environment it is probably the problem with file permissions:

https://stackoverflow.com/questions/36460874/laravel-5-errorexception-failed-to-open-stream-permission-denied
