### ISSUE TITLE
Change time of backups

### ISSUE THREAD

**Issue by davidprovaznikj** [mplodowski/backupmanager-plugin-public#17]
Hi,
how to change time of backup to another time?
Is there any possibility?
Thanks.

**Comment by mplodowski** [comment]
Hi,

can you explain in more details what you are trying to do?

You can use cron to schedule backup job to whatever time you want.

**Comment by davidprovaznikj** [comment]
Hi, I need start backup at 23:00h. Have you sample of cron command?

Standard october cron (every minute) I have configured correctly.

Thank you.

David Provazník

Dne ne 12. 7. 2020 17:12 uživatel Michał Płodowski <notifications@github.com>
napsal:

**Comment by mplodowski** [comment]
This is CRON that runs command at 23:00 every day:

0 23 * * *

Command to schedule application backup: php /your_project_path/artisan backup:run


Command to schedule database backup: php /your_project_path/artisan backup:run --only-db
