### ISSUE TITLE
 It does not delete the backups of the application

### ISSUE THREAD

**Issue by LlurensMartinezUtopig** [mplodowski/backupmanager-plugin-public#18]
Good morning,
First of all, I would like to thank you for the effort dedicated to the development of this plugin, for us it is a lifesaver, thanks to it we can sleep peacefully at night.
Everything works great for us, but we have programmed it to do a backup cleaning of the application every 7 days but it does not do it. Instead, cleaning DB backups works. Does this functionality work well for you? If you need to know any information, do not hesitate to ask me. 

Thank you very much

October version v1.0.469

**Comment by mplodowski** [comment]
What is your config for cleaning old backups looks like?

Does it clean old backups when you run command manually from backend or from command line?

**Comment by LlurensMartinezUtopig** [comment]
I have manually deleted the old backups and only deleted those from the DB, the application keeps them.

My Config is:
       - Scheculer
                 - Database backup: DAILY
                 - Application backup:  DAILY
                 - Cleanup old backups:  DAILY
        - Cleanup
                 - Keep all backups for days:  7
                 - Keep weekly backups for weeks:  8
                 - Keep yearly backups for years:  2
                 - Keep daily backups for days:  7
                 - Keep monthly backups for months:  4
                 - Delete oldest backups when using more megabytes than: 10000

**Comment by mplodowski** [comment]
Those are the rules used for cleaning backups:

Rule #1: it will never delete the latest backup regardless of its size or age
Rule #2: it will keep all backups for the number of days specified in keepAllBackupsForDays
Rule #3: it will only keep daily backups for the number of days specified in keepDailyBackupsForDays for all backups older than those covered by rule #2
Rule #4: it will only keep weekly backups for the number of months specified in keepMonthlyBackupsForMonths for all backups older than those covered by rule #3
Rule #5: it'll only keep yearly backups for the number of years specified in keepYearlyBackupsForYears for all backups older than those covered by rule #4
Rule #6: it will start deleting old backups until the volume of storage used is lower than the amount specified in deleteOldestBackupsWhenUsingMoreMegabytesThan.

So try to adjust your settings. For example:

- Keep all backups for days: 7
- Keep weekly backups for weeks: 0
- Keep yearly backups for years: 0
- Keep daily backups for days: 7
- Keep monthly backups for months: 0
- Delete oldest backups when using more megabytes than: 10000

**Comment by LlurensMartinezUtopig** [comment]
Good morning,
Sorry for the delay, I've been testing the changes you proposed but the result remains the same, the old database backups are deleted but not the old application backups, neither manually nor automatically.

**Comment by mplodowski** [comment]
Hmm, there is no difference in database or application backups when it comes to clearing backups.

Maybe there is some error when application backup is deleted. Please look inside application logs or server logs.

What are the size of the application backups?
