### ISSUE TITLE
ZipArchive::close(): Read error: No such file or directory 

### ISSUE THREAD

**Issue by LlurensMartinezUtopig** [mplodowski/backupmanager-plugin-public#19]
Hi,

The other day it came from one project, and today from other project, with the same error

Exception message: ZipArchive :: close (): Read error: No such file or directory

Do you have any idea what might have happened? 

Thank you

**Comment by mplodowski** [comment]
This may be caused by temporary files.

You should add temporary files to ignore list in backup config.

What is your include and exclude files config looks like?

**Comment by LlurensMartinezUtopig** [comment]
The include is empty and Exclude: vendor and node_modules

**Comment by mplodowski** [comment]
Most likely this issue is caused by temporary files located in storage directory.

Please try add `storage` to exclude section.

**Comment by mplodowski** [comment]
Does this solve your issue?
