### ISSUE TITLE
Error, Target [Spatie\Backup\Tasks\Cleanup\CleanupStrategy]  is not instantiable while building

### ISSUE THREAD

**Issue by omidmm16** [mplodowski/backupmanager-plugin-public#21]
Hi, 
I installed backupmanager, 
but I got an Error, mentioned bellow,

"Target [Spatie\Backup\Tasks\Cleanup\CleanupStrategy] is not instantiable while building [Spatie\Backup\Commands\CleanupCommand]." on line 978 of  /html/vendor/laravel/framework/src/Illuminate/Container/Container.php

please help me , to solve  the issue,

**Comment by mplodowski** [comment]
What version of Laravel and OctoberCMS do you use?
