### ISSUE TITLE
Error after updating to latest version 4.2

### ISSUE THREAD

**Issue by kombimedia** [mplodowski/backupmanager-plugin-public#23]
Hi there,

I have updated to the latest version of BackupManager - v4.2, and am now seeing an error when opening BackupManager in the admin dashboard.
I am running the latest build of OctoberCMS v2.1.8.

    Argument 1 passed to Spatie\Backup\Tasks\Monitor\HealthChecks\MaximumStorageInMegabytes::__construct() must be of 
    the type int, null given, called in /Users/responsive/Documents/Valet-Sites/responsiveweb/vendor/spatie/laravel- 
    backup/src/Tasks/Monitor/BackupDestinationStatusFactory.php on line 46

    ~/vendor/spatie/laravel-backup/src/Tasks/Monitor/HealthChecks/MaximumStorageInMegabytes.php line 14
    14: public function __construct(int $maximumSizeInMegaBytes = 5000)

Hope you can help.

Cy

**Comment by mplodowski** [comment]
Go to BackupManager Settings -> Monitoring tab

Set the value of "Storage used may not be higher than megabytes" to 5000.

**Comment by mplodowski** [comment]
It also should be fixed after update.

**Comment by kombimedia** [comment]
@mplodowski thanks for getting this sorted so quickly!

I can confirm that the v4.2.1 update has fixed the issue. Manually inputting a max file size limit also fixed the error.

Cheers
