### ISSUE TITLE
Website error after update on October 1.x

### ISSUE THREAD

**Issue by frasjaf** [mplodowski/backupmanager-plugin-public#24]
i have october cms v1 and got this problem afer updating the plugin
Undefined index: newestBackupsShouldNotBeOlderThanDays
/var/www/vhosts/soske.me/suma.soske.me/plugins/renatio/backupmanager/vendor/spatie/laravel-backup/src/Tasks/Monitor/BackupDestinationStatusFactory.php line 25

**Comment by mplodowski** [comment]
Do you use Laravel 6 or Laravel 5.5?

**Comment by mplodowski** [comment]
The last version which supports October 1.x is 4.1.0.

I recommend you to disable updates for this plugin until you upgrade to October 2.x

Here is zip file, so you can revert your changes.

[backupmanager-plugin-4.1.0.zip](https://github.com/mplodowski/backupmanager-plugin-public/files/7231272/backupmanager-plugin-4.1.0.zip)
