### ISSUE TITLE
Undefined constant ZipArchive::EM_AES_128 issue

### ISSUE THREAD

**Issue by disvst** [mplodowski/backupmanager-plugin-public#26]
I'm getting this error just after a fresh install on a LAMP environment (PHP 8.0). No problem in my local environment. 

Would you know how to solve this? 

If useful 
```
Zip | enabled
Zip version | 1.19.4
Libzip version | 1.1.2

```

**Comment by mplodowski** [comment]
I never get this error before. Maybe the LibZip library is outdated. I see that latest version is 1.8.0.

**Comment by disvst** [comment]
I just tried to remove your plugin but here is the error I get, even if it's removed 

`Class "Olssonm\BackupShield\BackupShieldServiceProvider" not found`

**Comment by mplodowski** [comment]
Try to run `composer update` in project root.

**Comment by disvst** [comment]
I won't be able to test it on another production environment with an updated Libzip version, so let's close this for now and thanks for your help.
