### ISSUE TITLE
Archive encryption seems to have stopped working after October v3 upgrade

### ISSUE THREAD

**Issue by joseph-d** [mplodowski/backupmanager-plugin-public#31]
**Describe the bug**
Looking back at backup archives, it seems that they are no longer being encrypted from the date that I moved from October v2 to October v3.

Previously, the archive would contain another archive called backup.zip which required a passphrase to extract it. But now the archive simply contains a directory called db-dumps with the .sql file inside.

**To Reproduce**

Wait for the schedule to perform a backup and then inspect the archive.

**Expected behavior**
An encrypted archive to be saved to the filesystem

**October version**
3.1.28

**Plugin version**

`composer show renatio/backupmanager-plugin` reports it as 5.1.8 but "Settings|System Updates|Manage Plugins" in the October backend shows it as 4.3.0. I believe October is showing the wrong version but I don't know how to prove it other thwn by running the composer show command.

**Additional context**
I haven't changed any of the backup settings between transitioning from October v2 to v3. I simply updated the plugin to the latest version in composer.json. The plugin appears to have been working properly otherwise, following the correct schedules,  zipping the archive, cleaning old backups etc. It's just the encryption that seems to have stopped working.

**Comment by mplodowski** [comment]
Fixed in v5.1.9.
