### ISSUE TITLE
Backups cannot be started at all...

### ISSUE THREAD

**Issue by bernfried** [mplodowski/backupmanager-plugin-public#33]
Hi, I just have bought and installed your plugin on a new website project. When I try to start an application or database backup I always get following error:

Call to undefined function Spatie\Backup\Commands\consoleOutput()

Did I miss something? I use the latest October CMS Version 3.2.12.

I hope you can help me. 
Regards,
Bernfried

**Comment by mplodowski** [comment]
What version of PHP are you using?

Do you test locally? If so what is your local setup?

I tested locally on Laravel Valet with PHP 8.1 and October 3.2.12 and is working.

Can you paste full debug log?

**Comment by bernfried** [comment]
1. We use PHP 8.1. 
2. Locally I have used the latest Docker version and their it works fine.

Stack Trace...
[2023-02-06 12:58:13] local.ERROR: Error: Call to undefined function Spatie\Backup\Commands\consoleOutput() in /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php:18
Stack trace:
#0 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Spatie\Backup\Commands\BackupCommand->handle()
#1 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#2 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#3 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(October\Rain\Foundation\Application), Array, Object(Closure))
#4 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\Container\BoundMethod::call(Object(October\Rain\Foundation\Application), Array, Array, NULL)
#5 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#6 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/symfony/console/Command/Command.php(312): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#7 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Console/Command.php(153): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#8 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(28): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#9 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/symfony/console/Application.php(1022): Spatie\Backup\Commands\BaseCommand->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#10 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand(Object(Spatie\Backup\Commands\BackupCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#11 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#12 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#13 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Console/Application.php(194): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#14 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(336): Illuminate\Console\Application->call('backup:run', Array, NULL)
#15 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): Illuminate\Foundation\Console\Kernel->call('backup:run', Array)
#16 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/plugins/renatio/backupmanager/controllers/Backups.php(41): Illuminate\Support\Facades\Facade::__callStatic('call', Array)
#17 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/modules/system/traits/DependencyMaker.php(29): Renatio\BackupManager\Controllers\Backups->onCreate()
#18 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/modules/backend/classes/Controller.php(604): Backend\Classes\Controller->makeCallMethod(Object(Renatio\BackupManager\Controllers\Backups), 'onCreate', Array)
#19 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/modules/backend/classes/Controller.php(448): Backend\Classes\Controller->runAjaxHandler('onCreate')
#20 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/modules/backend/classes/Controller.php(256): Backend\Classes\Controller->execAjaxHandlers()
#21 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/modules/backend/classes/BackendController.php(132): Backend\Classes\Controller->run('index', Array)
#22 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Backend\Classes\BackendController->run('renatio/backupm...')
#23 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction('run', Array)
#24 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Backend\Classes\BackendController), 'run')
#25 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#26 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\Routing\Route->run()
#27 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
#34 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#41 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#42 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#43 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/october/rain/src/Router/CoreRouter.php(32): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#44 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#45 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#46 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(23): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#51 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#52 /is/htdocs/wp1009029_GHGJ5INXIA/www-ocms/index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#53 {main}

**Comment by mplodowski** [comment]
Do you run docker on Windows?

**Comment by bernfried** [comment]
No, on Mac

**Comment by bernfried** [comment]
But the problems appear on a Host Europe Web Pack, which is an Linux environment. As said, in my Docker DEV environment everything works fine. It's just on the Host Europe server not working.

**Comment by mplodowski** [comment]
O sorry, I misunderstood you before.

Hmm this seems like some hosting or composer issue.

1. Do you use `composer` on this hosting? How do you install project on this hosting?
2. Do you also use PHP 8.1 on hosting?
3. Is proc_open enabled on hosting?

**Comment by bernfried** [comment]
1. I installed october cms via FTP transfer and adjusted the necessary files and permissions afterwards. I have no SSH access as it is not supported for such "Web Pack" offers.
2. Yes, PHP 8.1 is activated on that Web Pack instance.
3. proc_open: no idea :-( How can I check that?

**Comment by bernfried** [comment]
May be this helps. That should be the phpinfo() how it is setup on my server: http://webserver-php81.hosteurope-infos.de/phpinfo.php

**Comment by mplodowski** [comment]
This is only my guess, but I think this can be the issue how the project is installed. Eg. Copying files with FTP and not using composer may lead to this behavior.

It looks like composer cannot load the vendor package function consoleOutput().

You can try to two things:

1. Remove /vendor folder on hosting and upload it again from local.

2. Locally go to plugins/renatio/backupmanager. Then here run `composer install`. It will create /vendor folder. Upload this folder to hosting in the same location.

I don't think I can help you more with this, if both methods will not resolve the issue.

**Comment by bernfried** [comment]
Thank you for your quick responses and help. I will try this and let you know, if it works. Otherwise I will check if I change the server to one, where I can use ssh and run composer for the installation. Have a good evening.
