### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by KensingtonWebmaster** [mplodowski/backupmanager-plugin-public#34]
**Describe the bug**
When I clicked on the "Application Backup" button shows me "<html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx/1.25.3</center> </body> </html>      "

**Screenshots**
![Screenshot 2024-02-05 162351](https://github.com/mplodowski/backupmanager-plugin-public/assets/93997604/bcdb1dcc-7fb5-44d5-9470-8ae475aa6305)

**October version**
 "october/rain": "^3.5",
**Plugin version**
"renatio/backupmanager-plugin": "^5.1"
**Laravel version**
Laravel Framework 9.52.16

**Additional context**
But I can run the command "php artisan backup:run " to backup the project on the serve side. Could you please help me fix the Client-side problem,

**Comment by mplodowski** [comment]
Hi,

the issue is php max execution time is set by default to 30s. Application backup depends on size of your project files, so it take a lot of time to process. 

Please see the the documentation info about this:

https://github.com/mplodowski/backupmanager-plugin-public?tab=readme-ov-file#maximum-execution-time-error

**Comment by KensingtonWebmaster** [comment]
![Screenshot 2024-02-06 111400](https://github.com/mplodowski/backupmanager-plugin-public/assets/93997604/163d328e-2237-45e6-853e-4f1e47590cab)
Hi, I did add increase the execution time, I **add** the "ini_set('max_execution_time', '100000') " this code to the php,ini file, and **increase** the " @set_time_limit(0); ini_set('max_input_time', 0);  ini_set('max_execution_time', 0);" from 0 to  "@set_time_limit(100000); ini_set('max_input_time', 100000); ini_set('max_execution_time', 100000);" but it still shows me this error. I don't know why it still show me that, thank you.
![image](https://github.com/mplodowski/backupmanager-plugin-public/assets/93997604/f011ee3e-5477-43bb-86fc-a26846c2c414)

**Comment by mplodowski** [comment]
The error clearly states that your max execution time is still 30 seconds.

I recommend you to use scheduler to run application backups.
