### ISSUE TITLE
zip files seem to be corrupted

### ISSUE THREAD

**Issue by disvst** [mplodowski/backupmanager-plugin-public#8]
Hello,

I'm trying to download a backup file from the back-end and it seems to be corrupted. Could you please tell me where the backups are stored in order to look a little closer on the FTP?

**Comment by mplodowski** [comment]
Hi,

backups are stored at `/storage/app/{your_app_name}/`.

**Comment by mplodowski** [comment]
Did you find an issue?

**Comment by mplodowski** [comment]
If this issue is still relevant or you would like to see it actioned, please respond and I will re-open this issue.
