### ISSUE TITLE
October CMS will fail to be installed

### ISSUE THREAD

**Issue by Yoshiro-Sasagawa** [mplodowski/backupmanager-plugin-public#9]
Hi, it could not be a bug but this plugin causes installation failure of October CMS except fresh one.

If the plugin holds reference to a development database, then CMS installation will be failed on production environment.

it could be a problem when making multiple sites.
I miss some settings?

**Comment by mplodowski** [comment]
Please provide more details, step by step what you are doing.

**Comment by Yoshiro-Sasagawa** [comment]
1.  fresh install October CMS, and BackupManager plugin by Attaching Project.
    Let's say that is CMS1.
2. copy CMS1, that is CMS2.
3. do "php artisan october:install" on CMS2 root directory and change database or URL or something.
4 copy CMS2, that is CMS3.
5 trying "php artisan october:install" on CMS3 root directory, then I've got a "SQLSTATE[***]: Base table or view not found:........"  error.

Sorry, I made a mess.
the plugin probably has some files that artisan's installation command cannot reach to.

**Comment by mplodowski** [comment]
1. All paid plugins has license per project. So you shouldn't use them on different multiple projects.
2. I don't think that October install command will run plugins migrations. You must use `php artisan october:up` command after.

**Comment by Yoshiro-Sasagawa** [comment]
You're not saying that we should pay for each CMS on docker containers in one project, are you?

the problem here is that the plugin doesn't allow me to change database one to another,
like test_db to production_db.

Editing config/database.php after fresh install October CMS and BackupManager, then `october:up` command will also reproduce the error.

If I remove the plugin's folder, migration can be succeeded.

**Comment by mplodowski** [comment]
I don't know how you use this plugin and on how many projects etc.

I recommend you to read October articles in this subject:

https://octobercms.com/help/license/regular

https://octobercms.com/help/license/faqs

As you describe this, you use single license for multiple projects, which is legally forbidden.

But let's back to the topic:

I found that issue is in `Plugin.php` and function `registerSchedule()`. I added a check there if the settings table exists.

It will be fixed in next version.

If you want to apply fix manually:

```
public function registerSchedule($schedule)
{
    if ( ! \Schema::hasTable('system_settings')) {
        return;
    }

    (new Schedule($schedule))
        ->databaseBackup()
        ->appBackup()
        ->cleanOldBackups();
}
```

**Comment by Yoshiro-Sasagawa** [comment]
Thank you for offering me the docs.
now I knew that I should stop to use one payed plugin with several docker containers.

But just make it clear, its not a license problem.

The document says,
> A Website is defined as a single installation of OctoberCMS that is accessible from a single webpage and is controlled by a single back-end administration area, operated by a single organization or person.

So to switch database is not forbidden and issue is still there.

Anyway the plugin helps a lot!

**Comment by mplodowski** [comment]
Yeah, I agree. Please wait for official fix then.

**Comment by mplodowski** [comment]
Please update to version 3.0.2.

I tested like this:

1. Install fresh October.
2. Install BackupManager plugin.
3. Change database to new clean database.
4. Run `php artisan october:up`.

The migrations for October and for backup plugin runs successfully.

**Comment by mplodowski** [comment]
If this issue is still relevant or you would like to see it actioned, please respond and I will re-open this issue.
